### ISSUE TITLE
Discovery 1: update graph bins

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/seda-site#137]
[binscatter_jan26.xlsx](https://github.com/Hyperobjekt/seda-map/files/5881879/binscatter_jan26.xlsx)
We’ve updated the Discovery 1 underlying data with the newest SEDA 4.0 data. Attached is the excel file of the new coordinates for the bins (tab 1), as well as the equation for the fit line (tab 2). 

@alegzandach will xls work or do you need this in csv?

**Comment by laurendoone** [comment]
@alegzandach oops sorry! moved to seda-site

**Comment by alegzandach** [comment]
@laurendoone thanks! I see now that i can do it sorry! 

Also, the data provided results in a chart with 2 quadrants instead of 4. I'm not sure how the new data relates to the old but none of these bins have shrinking gaps? Maybe this isn't a big deal!
![discovery1](https://user-images.githubusercontent.com/12611947/106059592-eeb8ae00-60c0-11eb-9556-380535695ec3.JPG)

**Comment by laurendoone** [comment]
waiting on a response from the client...

**Comment by laurendoone** [comment]
@alegzandach client says this is correct! "There have been some changes to the underlying data since the version we sent from December and we’ve moved from using the unsuppressed public sample to the suppressed public sample, which is why there’s a shift in the axis. "
