### ISSUE TITLE
a11y: reduced motion

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/seda-site#21]
would be nice if we could turn off animations for users that have a prefer reduced motion setting enabled.

i've done it in the explorer with this media query and it works great.

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

**Comment by amygroshek** [comment]
@Lane I understand the sentiment but am curious what kind of animations? Animated SVGs makes sense to me. We only have a few of those. Or are you thinking of Animations of jQ UI accordion tabs? Or the animated hide/show of the navigation menu?

**Comment by Lane** [comment]
yeah, animated SVGs on the homepage are the big one i think.

fades aren't as big of a concern, and it looks like the jQ UI tabs already have animations disabled if you have the prefer reduced motion setting enabled.

**Comment by amygroshek** [comment]
Pushed an implementation for this that touches both the CSS and some of the JS inits. The animated SVG in the header animates all on its own, and the PNG fallback and the header in general is styled only for smaller-screen devices, so I'm leaving that for now. It's a much lower contrast image so hopefully that won't affect users with motion sensitivity as much. We can always revisit.

**Comment by Lane** [comment]
sounds good, thanks.  i'm going to reopen for the hero animation, i should have time to get to it this weekend.

**Comment by amygroshek** [comment]
At present, there are two versions of many elements on the page, half are for small-screen devices, half are for desktop. There are additional rules regarding browsers without svg support, but these are mostly mobile browsers. A reduce-motion preference might occur across any of these devices, but the layouts are so locked into the device-specific markup that it becomes very difficult to implement. When implementing a11y, I've worked around that issues resulting from the extraneous markup using aria-hidden and some other techniques, but I feel that this issue points to a larger concern about that markup strategy, maybe a larger conversation. IMO wherever at all possible we should not duplicate elements, and instead use CSS to manage their ordering and visibility, and simple transitions (of opacity, for example) should be handled by classes that are assigned to or removed from elements, rather than directly on the element with JS. Then we could set this media query like any other, and adjust the layouts, without then having to cherry-pick elements across two different sets of markup... I know @james-minton had reasons for implementing it this way, though, so those should def be considered.
